version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      non-major:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    groups:
      non-major:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      non-major:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/build_tools"
    schedule:
      interval: "weekly"
    groups:
      non-major:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pip"
    directory: "/mkdocs"
    schedule:
      interval: "weekly"
    groups:
      non-major:
        update-types:
          - "minor"
          - "patch"
