version: 2
updates:
  # 1. GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-dependencies:
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"
          - "patch"

  # 2. Go Modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    labels:
      - "dependencies"
      - "go"
    groups:
      go-non-major:
        update-types:
          - "minor"
          - "patch"

  # 3. Docker (Root)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "docker"
    groups:
      non-major:
        update-types:
          - "minor"
          - "patch"

  # 4. Docker (Tools)
  - package-ecosystem: "docker"
    directory: "/tools"
    schedule:
      interval: "weekly"
    labels:
      - "docker"
      - "tools"
    groups:
      non-major:
        update-types:
          - "minor"
          - "patch"
