services:
  test:
    build:
      context: .
      dockerfile: build/Dockerfile.test
    volumes:
      - .:/app
      - go-cache:/go-cache
      - go-mod-cache:/go-mod-cache

volumes:
  go-cache:
  go-mod-cache:
