name: golangci-lint

on: workflow_call

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Install Libraries on Linux
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y fuse libfuse-dev rpm pkg-config
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.8
          args: --timeout=5m
          install-mode: goinstall
