name: mkdocs

on: workflow_call

permissions:
  contents: write

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - uses: actions/cache@v5
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('mkdocs/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        working-directory: ./mkdocs
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt

      - name: Build docs
        working-directory: ./mkdocs
        run: |
          mkdocs build

      - name: Set up git author
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy docs (Master)
        if: github.ref == 'refs/heads/master'
        working-directory: ./mkdocs
        run: |
          echo "${CUSTOM_DOMAIN}" > "docs/CNAME"
          echo -e "User-agent: *\nDisallow: /v*.*/\nSitemap: https://${CUSTOM_DOMAIN}/sitemap.xml" > "docs/robots.txt"
          git fetch origin gh-pages --verbose
          mike deploy master dev --push
        env:
          CUSTOM_DOMAIN: distribyted.com
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}

      - name: Deploy docs (Versions)
        if: startsWith(github.ref, 'refs/tags/v')
        working-directory: ./mkdocs
        run: |
          git fetch origin gh-pages --verbose
          mike deploy ${GITHUB_REF##*/} latest --push --update-aliases
        env:
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
